services:
  - type: web
    name: cityflow
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cityflow-db
          property: connectionString

databases:
  - name: cityflow-db
    plan: free
    databaseName: cityflow
    user: cityflow_user
